localCapture:
  # Maximum file size per capure, in kilobytes
  maxFilesize: 50000
  # Maximum amount of pcaps to store
  maxPcaps: 20
  # Whether to enable compression of the packet captures
  enableCompression: true
  # What to call the initial file. Note filename will be appended with sequence number and timestamp.
  outputFile: /etc/localcapture/localCapture.pcap
  # Which ports to capture traffic on
  portList:
  - 80
  - 443